repos:
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
- repo: https://github.com/timothycrosley/isort
  rev: 5.3.0
  hooks:
  - id: isort
