repos:
- repo: https://github.com/ambv/black
  rev: 24.2.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    additional_dependencies: [ flake8-bugbear ]
- repo: https://github.com/timothycrosley/isort
  rev: 5.13.2
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: debug-statements
