[build-system]
requires = [
    "poetry-core>=2.0.0,<3.0.0",
]
build-backend = "poetry.core.masonry.api"

[project]
name = "aiographql-client"
version = "1.2.0a0"
description = "An asyncio GraphQL client built on top of aiohttp and graphql-core-next"
license = "MIT"
readme = "README.md"
requires-python = ">=3.10,<4.0"
keywords = [
    "aiohttp",
    "asyncio",
    "client",
    "graphql",
    "graphql-core",
    "graphql-core-next",
]
dynamic = [
    "classifiers",
]
dependencies = [
    "cafeteria-asyncio >=0.3,<0.4",
    "aiohttp >=3.5,<4.0",
    "graphql-core >=3.0,<4.0",
    "ujson >=2",
]

[[project.authors]]
name = "Arun Neelicattu"
email = "arun.neelicattu@gmail.com"

[project.urls]
repository = "https://github.com/abn/aiographql-client"

[tool.poetry]
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Framework :: AsyncIO",
]
requires-poetry = ">=2.0"
[[tool.poetry.packages]]
include = "aiographql"
from = "src"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
src_paths = [
    "src",
    "test",
]
known_first_party = "aiographql"

[tool.pytest.ini_options]
minversion = "6.0"
asyncio_mode = "auto"
addopts = "--cov --cov-append --cov-report=term"
testpaths = [
    "tests",
]

[tool.coverage.run]
branch = true
parallel = true
data_file = ".coverage/data"
source = [
    "aiographql",
]
omit = [
    "tests/*",
]

[tool.coverage.paths]
source = [
    "src",
]

[tool.coverage.report]
skip_empty = true
ignore_errors = true
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]

[tool.coverage.html]
directory = ".coverage/html"

[tool.coverage.xml]
output = ".coverage/coverage.xml"

[tool.coverage.json]
output = ".coverage/coverage.json"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1"
pytest-asyncio = "^0.23"
pytest-cov = "^5.0"
pytest-mock = "^3.14"

[tool.poetry.group.dev.dependencies.coverage]
version = "^7.4"
extras = [
    "toml",
]
