from __future__ import annotations

import asyncio
import contextlib
import dataclasses
import uuid

from enum import Enum
from typing import TYPE_CHECKING
from typing import Any
from typing import cast


if TYPE_CHECKING:
    import aiohttp

    from aiographql.client.transport.base import GraphQLSubscriptionTransport
    from aiographql.client.request import GraphQLRequest

from cafeteria.asyncio.callbacks import CallbackRegistry
from cafeteria.asyncio.callbacks import CallbackType
from cafeteria.asyncio.callbacks import SimpleTriggerCallback

from aiographql.client.request import GraphQLRequestContainer
from aiographql.client.response import GraphQLBaseResponse
from aiographql.client.response import GraphQLResponse
from aiographql.client.transport.resolver import get_default_subscription_transport


if TYPE_CHECKING:
    from collections.abc import Iterable
    from typing import TypeAlias

    from aiographql.client.codec import GraphQLCodec
    from aiographql.client.serializer import GraphQLSerializer


class GraphQLSubscriptionEventType(Enum):
    """
    GraphQL Subscription Event Types
    """

    CONNECTION_INIT = "connection_init"
    CONNECTION_ACK = "connection_ack"
    CONNECTION_ERROR = "connection_error"
    CONNECTION_TERMINATE = "connection_terminate"
    START = "start"
    DATA = "data"
    ERROR = "error"
    COMPLETE = "complete"
    STOP = "stop"
    KEEP_ALIVE = "ka"


if TYPE_CHECKING:
    CallbacksType: TypeAlias = (
        CallbackRegistry
        | dict[GraphQLSubscriptionEventType, CallbackType | list[CallbackType]]
    )
else:
    CallbacksType = Any


@dataclasses.dataclass(frozen=True)
class GraphQLSubscriptionEvent(GraphQLBaseResponse):
    """
    GraphQL subscription event wrapping the payload received from the server.

    :param subscription_id: The id of the subscription that generated this event.
    """

    subscription_id: str | None = dataclasses.field(default=None)

    @property
    def id(self) -> str | None:
        """The id of the event, if available."""
        return self.json.get("id")

    @property
    def type(self) -> GraphQLSubscriptionEventType | None:
        """The type of event (:class:`GraphQLSubscriptionEventType`)."""
        try:
            return GraphQLSubscriptionEventType(self.json.get("type"))
        except ValueError:
            return None

    @property
    def payload(self) -> GraphQLResponse | str | None:
        """The id of the subscription that generated this event."""
        payload = self.json.get("payload")
        if payload is not None:
            if self.type in (
                GraphQLSubscriptionEventType.DATA,
                GraphQLSubscriptionEventType.ERROR,
            ) and isinstance(payload, dict):
                return GraphQLResponse(request=self.request, json=payload)
            return cast("str", payload)
        return None


@dataclasses.dataclass(frozen=True)
class GraphQLSubscription(GraphQLRequestContainer):
    """
    Subscription container, with an attached
    :class:`cafeteria.asyncio.callbacks.CallbackRegistry`. When subscribed,
    the `task` will be populated with the :class:`asyncio.Task` instance.

    By default the subscription will be stopped, if an error, connection error or
    complete (:class:`GraphQLSubscriptionEventType`) is received.

    Subscription instances are intended to be used as immutable objects. However,
    `callbacks` and `stop_event_types` can be updated after initialisation.

    :param id: A unique subscription identifier that will be passed into any events
        generated by this subscription.
    :param callbacks: A :class:`CallbackRegistry` containing a mapping of
        :class:`GraphQLSubscriptionEventType` callback methods to trigger.
    :param stop_event_types: Events that cause the subscription to stop. By default,
        connection error, query error or connection complete events received are
        considered stop events.
    :param protocols: GraphQL over WebSocket Sub-protocol used. This is optional, as
        this is only required for certain servers. When specified, this value is set as
        the Sec-WebSocket-Protocol header when a WebSocket connection is established.
    :param connection_init_payload: Extra fields for the `connection_init` payload.
    """

    id: str = dataclasses.field(default_factory=lambda: str(uuid.uuid4()), init=False)
    callbacks: CallbacksType | None = dataclasses.field(
        default_factory=CallbackRegistry
    )
    stop_event_types: list[GraphQLSubscriptionEventType] = dataclasses.field(
        default_factory=lambda: [
            GraphQLSubscriptionEventType.ERROR,
            GraphQLSubscriptionEventType.CONNECTION_ERROR,
            GraphQLSubscriptionEventType.COMPLETE,
        ]
    )
    protocols: str | Iterable[str] = dataclasses.field(default_factory=tuple)
    connection_init_payload: dict[str, Any] | None = dataclasses.field(default=None)
    serializer: GraphQLSerializer | None = dataclasses.field(default=None)
    transport: GraphQLSubscriptionTransport | None = dataclasses.field(default=None)
    task: asyncio.Task[Any] | None = dataclasses.field(
        default=None, init=False, compare=False
    )

    def __post_init__(
        self,
        headers: dict[str, str] | None,
        operation: str | None,
        variables: dict[str, Any] | None,
        codec: GraphQLCodec | None,
    ) -> None:
        super().__post_init__(
            headers=headers,
            operation=operation,
            variables=variables,
            codec=codec,
        )

        if isinstance(self.protocols, str):
            object.__setattr__(self, "protocols", (self.protocols,))

        if self.callbacks is None:
            object.__setattr__(self, "callbacks", CallbackRegistry())
        elif isinstance(self.callbacks, dict):
            object.__setattr__(
                self, "callbacks", CallbackRegistry(callbacks=self.callbacks)
            )

    def active(self) -> bool:
        """
        Check if the subscription is active.

        :return: `True` if subscribed and active.
        """
        return (
            self.task is not None and not self.task.done() and not self.task.cancelled()
        )

    def connection_init_request(self) -> dict[str, Any]:
        """
        Connection init payload to use when initiating a new subscription.

        :return: Connection initialise payload.
        """
        headers: dict[str, str] = {}
        if not isinstance(self.request, str):
            headers = self.request.headers

        payload = {**(self.connection_init_payload or {})}
        payload_headers = payload.get("headers")
        if not isinstance(payload_headers, dict):
            payload_headers = {}

        payload["headers"] = {**payload_headers, **headers}

        return {
            "type": GraphQLSubscriptionEventType.CONNECTION_INIT.value,
            "payload": payload,
        }

    def connection_start_request(self) -> dict[str, Any]:
        """
        Connection start payload to use when starting a subscription.

        :return: Connection start payload.
        """
        payload: dict[str, Any] = {}
        if not isinstance(self.request, str):
            payload = self.request.payload()
        return {
            "id": self.id,
            "type": GraphQLSubscriptionEventType.START.value,
            "payload": payload,
        }

    def connection_stop_request(self) -> dict[str, Any]:
        """
        Connection stop payload to use when stopping a subscription.

        :return: Connection stop payload.
        """
        return {"id": self.id, "type": GraphQLSubscriptionEventType.STOP.value}

    def is_stop_event(self, event: GraphQLSubscriptionEvent) -> bool:
        """
        Check if the provided *event* is configured as a stop even for this subscription.

        :param event: Event to check.
        :return: `True` if `event` is in `stop_event_types`.
        """
        return event.type in self.stop_event_types

    async def handle(self, event: GraphQLSubscriptionEvent) -> None:
        """
        Helper method to dispatch any configured callbacks for the specified event type.

        :param event: Event to dispatch callbacks for.
        """
        if (
            (event.id is None or event.id == self.id)
            and self.callbacks is not None
            and isinstance(self.callbacks, CallbackRegistry)
        ):
            self.callbacks.dispatch(event.type, event)

    async def _websocket_connect(
        self,
        endpoint: str,
        transport: GraphQLSubscriptionTransport,
        session: aiohttp.ClientSession | None = None,
    ) -> None:
        """
        Helper method to create websocket connection with specified *endpoint*
        using the specified :class:`GraphQLSubscriptionTransport`. Once connected, we
        initialise and start the GraphQL subscription; then wait for any incoming
        messages. Any message received via the websocket connection is cast into
        a :class:`GraphQLSubscriptionEvent` instance and dispatched for handling via
        :method:`handle`.

        :param endpoint: Endpoint to use when creating the websocket connection.
        :param transport: Transport to use when creating the websocket connection.
        :param session: Optional session to use when creating the websocket connection.
        """
        if self.serializer is None:
            # This should ideally be passed from client, but for safety:
            from aiographql.client.serializer import DefaultSerializer

            object.__setattr__(self, "serializer", DefaultSerializer())

        ws = await transport.subscribe(
            endpoint=endpoint,
            request=cast("GraphQLRequest", self.request),
            serializer=cast("GraphQLSerializer", self.serializer),
            protocols=self.protocols,
            session=session,
        )

        async with ws:

            def _serialize(value: Any) -> str:
                serialized = cast("GraphQLSerializer", self.serializer).dumps(value)
                return (
                    serialized.decode("utf-8")
                    if isinstance(serialized, bytes)
                    else serialized
                )

            await ws.send_str(_serialize(self.connection_init_request()))

            if self.callbacks is not None and isinstance(
                self.callbacks, CallbackRegistry
            ):
                self.callbacks.register(
                    GraphQLSubscriptionEventType.CONNECTION_ACK,
                    SimpleTriggerCallback(
                        function=ws.send_str,
                        data=_serialize(self.connection_start_request()),
                    ),
                )

            try:
                async for msg in ws:
                    # We assume the message type check is still relevant if it's aiohttp-like
                    # but different transports might have different message objects.
                    # For now, we maintain compatibility with aiohttp's WSMessage.
                    if hasattr(msg, "type"):
                        import aiohttp

                        if msg.type != aiohttp.WSMsgType.TEXT:
                            if msg.type == aiohttp.WSMsgType.ERROR:
                                break
                            continue
                        data = msg.data
                    else:
                        data = msg

                    event = GraphQLSubscriptionEvent(
                        subscription_id=self.id,
                        request=self.request,
                        json=cast("GraphQLSerializer", self.serializer).loads(data),
                    )
                    await self.handle(event=event)

                    if self.is_stop_event(event):
                        break
            except (asyncio.CancelledError, KeyboardInterrupt):
                await ws.send_str(_serialize(self.connection_stop_request()))

    async def _subscribe(
        self,
        endpoint: str,
        transport: GraphQLSubscriptionTransport | None = None,
        session: aiohttp.ClientSession | None = None,
    ) -> None:
        """
        Helper method wrapping :method:`GraphQLSubscription._websocket_connect` handling
        unique :class:`GraphQLSubscriptionTransport` resolution.

        :param endpoint: Endpoint to use when creating the websocket connection.
        :param transport: Optional transport to use.
        :param session: Optional session to use when creating the websocket connection.
        """
        actual_transport = (
            transport
            or self.transport
            or get_default_subscription_transport(endpoint=endpoint)
        )
        return await self._websocket_connect(
            endpoint=endpoint, transport=actual_transport, session=session
        )

    async def subscribe(
        self,
        endpoint: str,
        force: bool = False,
        transport: GraphQLSubscriptionTransport | None = None,
        session: aiohttp.ClientSession | None = None,
        wait: bool = False,
    ) -> None:
        """
        Create a websocket subscription and set internal task.

        :param endpoint: GraphQL endpoint to subscribe to
        :param force: Force re-subscription if already subscribed
        :param transport: Optional transport to use for requests
        :param session: Optional session to use for requests
        :param wait: If set to `True`, this method will wait until the subscription
            is completed, websocket disconnected or async task cancelled.
        """
        if self.active() and not force:
            return
        self.unsubscribe()
        task = asyncio.create_task(
            self._subscribe(endpoint=endpoint, transport=transport, session=session)
        )
        object.__setattr__(self, "task", task)

        if wait and self.task is not None:
            with contextlib.suppress(asyncio.CancelledError):
                await self.task

    def unsubscribe(self) -> None:
        """
        Unsubscribe current websocket subscription if active and clear internal task.
        """
        if self.active() and self.task is not None:
            with contextlib.suppress(asyncio.CancelledError):
                self.task.cancel()
        object.__setattr__(self, "task", None)

    async def unsubscribe_and_wait(self) -> None:
        task = self.task
        self.unsubscribe()
        if task is not None:
            with contextlib.suppress(asyncio.CancelledError):
                await task

    async def __aenter__(self) -> GraphQLSubscription:
        return self

    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        await self.unsubscribe_and_wait()
