name: Code Quality Checks

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main

  pull_request:
    branches:
      - '**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
    - uses: pre-commit/action@v3.0.1
