name: Publish Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: python

      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pipx install poetry

      - name: Build project for distribution
        if: ${{ steps.release.outputs.release_created }}
        run: poetry build

      - name: Publish to PyPI
        if: ${{ steps.release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@release/v1
