# workaround for https://github.com/actions/virtual-environments/issues/1281
name: Skip All Jobs

on:
  push:
    paths:
      - '!**'
      - 'docs/**'
    branches:
      - master
  pull_request:
    paths:
      - '!**'
      - 'docs/**'
    branches:
      - '**'

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  tests:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    # we do not need os specific runners here, using linux is quicker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [Ubuntu, MacOS, Windows]
        python-version: [3.7, 3.8, 3.9]
    steps:
      - run: exit 0
